spring.application.name=ecom-proj
server.port=8080
spring.datasource.url=jdbc:h2:mem:manoj
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=CommerceHubSecretKeyForJWTAuthenticationMustBeAtLeast256BitsLong2024
jwt.expiration=86400000

